services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports:
      - "20497:5432"

  web:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn seniorproject.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info
    ports:
      - "10497:8000"    # <--- map ให้ user เข้า web โดยตรง
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media

volumes:
  pgdata:
