services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 20
   
     

  web:
      build: .
      restart: always
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "${PUBLIC_PORT}:8000"
      volumes:
        - ./app:/app
        - ./static:/app/static
        - ./media:/app/media

volumes:
  pgdata:
