# Generated by Django 5.1.3 on 2024-12-06 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('ว่าง', 'ว่าง'), ('กำลังนั่ง', 'กำลังนั่ง'), ('จอง', 'จอง')], max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableapp.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
