# Generated by Django 5.1.4 on 2025-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_zone_table_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
