# Generated by Django 5.1.3 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0004_remove_table_booking_date_remove_table_booking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
