# Generated by Django 5.1.3 on 2024-12-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_remove_booking_datetime_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table_name',
            new_name='table',
        ),
    ]
