# Generated by Django 5.1.4 on 2025-01-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('in_progress', 'กำลังเตรียม'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
