# Generated by Django 5.1.4 on 2024-12-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0009_menu_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('เมนูแนะนำ', 'เมนูแนะนำ'), ('ต้ม', 'ต้ม'), ('ผัด', 'ผัด'), ('แกง', 'แกง'), ('ทอด', 'ทอด')], default='recommend', max_length=20),
        ),
    ]
