# Generated by Django 5.1.4 on 2025-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0010_order_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x_position',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='table',
            name='y_position',
            field=models.IntegerField(default=100),
        ),
    ]
