# Generated by Django 5.1.4 on 2025-02-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0011_table_x_position_table_y_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อโปรโมชัน')),
                ('discount_type', models.CharField(choices=[('percent', 'ลดเป็น %'), ('fixed_price', 'กำหนดราคาตายตัว')], max_length=20, verbose_name='ประเภทส่วนลด')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='มูลค่าส่วนลด')),
                ('start_time', models.DateTimeField(verbose_name='เริ่มโปรโมชัน')),
                ('end_time', models.DateTimeField(verbose_name='สิ้นสุดโปรโมชัน')),
                ('is_active', models.BooleanField(default=True, verbose_name='โปรโมชันยังใช้งานอยู่')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tableapp.menu')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='tableapp.promotion')),
            ],
        ),
    ]
