# Generated by Django 5.1.4 on 2025-02-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0012_promotion_promotionmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_promotions', to='tableapp.menu'),
        ),
        migrations.AlterField(
            model_name='promotionmenu',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_menus', to='tableapp.promotion'),
        ),
    ]
