# Generated by Django 5.1.4 on 2025-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0014_alter_orderitem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='x_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_position',
            field=models.FloatField(default=0.0),
        ),
    ]
